// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SettingApi.Data;

#nullable disable

namespace SettingApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240213205709_InitialChangeToTPC")]
    partial class InitialChangeToTPC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SettingApi.Entities.Models.EmailSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDirectMessageEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMentionEnabled")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("EmailSettings", (string)null);
                });

            modelBuilder.Entity("SettingApi.Entities.Models.PushSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDirectMessageEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFollowEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMentionEnabled")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("PushSettings", (string)null);
                });

            modelBuilder.Entity("SettingApi.Entities.Models.SmsSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPasswordChangeEnabled")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("SmsSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
